<?php

namespace Database\Seeders;

use App\Models\CurrencyMap;
use Illuminate\Database\Seeder;

class CurrencyMapSeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            ['code' => 'AED', 'name' => 'UAE Dirham', 'aliases' => ['درهم', 'درهم إماراتي', 'د.إ']],
            ['code' => 'AFN', 'name' => 'Afghani', 'aliases' => []],
            ['code' => 'ALL', 'name' => 'Lek', 'aliases' => []],
            ['code' => 'AMD', 'name' => 'Armenian Dram', 'aliases' => []],
            ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder', 'aliases' => []],
            ['code' => 'AOA', 'name' => 'Kwanza', 'aliases' => []],
            ['code' => 'ARS', 'name' => 'Argentine Peso', 'aliases' => []],
            ['code' => 'AUD', 'name' => 'Australian Dollar', 'aliases' => ['A$']],
            ['code' => 'AWG', 'name' => 'Aruban Florin', 'aliases' => []],
            ['code' => 'AZN', 'name' => 'Azerbaijan Manat', 'aliases' => []],
            ['code' => 'BAM', 'name' => 'Convertible Mark', 'aliases' => []],
            ['code' => 'BBD', 'name' => 'Barbados Dollar', 'aliases' => []],
            ['code' => 'BDT', 'name' => 'Taka', 'aliases' => []],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'aliases' => []],
            ['code' => 'BHD', 'name' => 'Bahraini Dinar', 'aliases' => ['دينار بحريني', 'د.ب']],
            ['code' => 'BIF', 'name' => 'Burundi Franc', 'aliases' => []],
            ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'aliases' => []],
            ['code' => 'BND', 'name' => 'Brunei Dollar', 'aliases' => []],
            ['code' => 'BOB', 'name' => 'Boliviano', 'aliases' => []],
            ['code' => 'BRL', 'name' => 'Brazilian Real', 'aliases' => ['R$']],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'aliases' => []],
            ['code' => 'BTN', 'name' => 'Ngultrum', 'aliases' => []],
            ['code' => 'BWP', 'name' => 'Pula', 'aliases' => []],
            ['code' => 'BYN', 'name' => 'Belarusian Ruble', 'aliases' => []],
            ['code' => 'BZD', 'name' => 'Belize Dollar', 'aliases' => []],
            ['code' => 'CAD', 'name' => 'Canadian Dollar', 'aliases' => ['C$']],
            ['code' => 'CDF', 'name' => 'Congolese Franc', 'aliases' => []],
            ['code' => 'CHF', 'name' => 'Swiss Franc', 'aliases' => ['Fr']],
            ['code' => 'CLP', 'name' => 'Chilean Peso', 'aliases' => []],
            ['code' => 'CNY', 'name' => 'Yuan Renminbi', 'aliases' => ['¥', 'RMB']],
            ['code' => 'COP', 'name' => 'Colombian Peso', 'aliases' => []],
            ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'aliases' => []],
            ['code' => 'CUP', 'name' => 'Cuban Peso', 'aliases' => []],
            ['code' => 'CVE', 'name' => 'Cabo Verde Escudo', 'aliases' => []],
            ['code' => 'CZK', 'name' => 'Czech Koruna', 'aliases' => ['Kč']],
            ['code' => 'DJF', 'name' => 'Djibouti Franc', 'aliases' => []],
            ['code' => 'DKK', 'name' => 'Danish Krone', 'aliases' => ['kr']],
            ['code' => 'DOP', 'name' => 'Dominican Peso', 'aliases' => []],
            ['code' => 'DZD', 'name' => 'Algerian Dinar', 'aliases' => ['دينار جزائري', 'د.ج']],
            ['code' => 'EGP', 'name' => 'Egyptian Pound', 'aliases' => ['جنيه مصري', 'ج.م']],
            ['code' => 'ERN', 'name' => 'Nakfa', 'aliases' => []],
            ['code' => 'ETB', 'name' => 'Ethiopian Birr', 'aliases' => []],
            ['code' => 'EUR', 'name' => 'Euro', 'aliases' => ['€', 'يورو']],
            ['code' => 'FJD', 'name' => 'Fiji Dollar', 'aliases' => []],
            ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'aliases' => []],
            ['code' => 'GBP', 'name' => 'Pound Sterling', 'aliases' => ['£', 'جنيه استرليني']],
            ['code' => 'GEL', 'name' => 'Lari', 'aliases' => []],
            ['code' => 'GHS', 'name' => 'Ghana Cedi', 'aliases' => []],
            ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'aliases' => []],
            ['code' => 'GMD', 'name' => 'Dalasi', 'aliases' => []],
            ['code' => 'GNF', 'name' => 'Guinean Franc', 'aliases' => []],
            ['code' => 'GTQ', 'name' => 'Quetzal', 'aliases' => []],
            ['code' => 'GYD', 'name' => 'Guyana Dollar', 'aliases' => []],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'aliases' => ['HK$']],
            ['code' => 'HNL', 'name' => 'Lempira', 'aliases' => []],
            ['code' => 'HTG', 'name' => 'Gourde', 'aliases' => []],
            ['code' => 'HUF', 'name' => 'Forint', 'aliases' => ['Ft']],
            ['code' => 'IDR', 'name' => 'Rupiah', 'aliases' => ['Rp']],
            ['code' => 'ILS', 'name' => 'New Israeli Sheqel', 'aliases' => ['₪', 'شيكل']],
            ['code' => 'INR', 'name' => 'Indian Rupee', 'aliases' => ['₹', 'روبية']],
            ['code' => 'IQD', 'name' => 'Iraqi Dinar', 'aliases' => ['دينار عراقي', 'د.ع']],
            ['code' => 'IRR', 'name' => 'Iranian Rial', 'aliases' => ['ريال إيراني', 'تومان']],
            ['code' => 'ISK', 'name' => 'Iceland Krona', 'aliases' => []],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'aliases' => []],
            ['code' => 'JOD', 'name' => 'Jordanian Dinar', 'aliases' => ['دينار أردني', 'د.أ']],
            ['code' => 'JPY', 'name' => 'Yen', 'aliases' => ['¥', 'ين']],
            ['code' => 'KES', 'name' => 'Kenyan Shilling', 'aliases' => []],
            ['code' => 'KGS', 'name' => 'Som', 'aliases' => []],
            ['code' => 'KHR', 'name' => 'Riel', 'aliases' => []],
            ['code' => 'KMF', 'name' => 'Comorian Franc', 'aliases' => []],
            ['code' => 'KRW', 'name' => 'Won', 'aliases' => ['₩']],
            ['code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'aliases' => ['دينار كويتي', 'د.ك']],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'aliases' => []],
            ['code' => 'KZT', 'name' => 'Tenge', 'aliases' => ['₸']],
            ['code' => 'LAK', 'name' => 'Lao Kip', 'aliases' => []],
            ['code' => 'LBP', 'name' => 'Lebanese Pound', 'aliases' => ['ليرة لبنانية', 'ل.ل']],
            ['code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'aliases' => []],
            ['code' => 'LRD', 'name' => 'Liberian Dollar', 'aliases' => []],
            ['code' => 'LSL', 'name' => 'Loti', 'aliases' => []],
            ['code' => 'LYD', 'name' => 'Libyan Dinar', 'aliases' => ['دينار ليبي', 'د.ل']],
            ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'aliases' => ['درهم مغربي', 'د.م']],
            ['code' => 'MDL', 'name' => 'Moldovan Leu', 'aliases' => []],
            ['code' => 'MGA', 'name' => 'Malagasy Ariary', 'aliases' => []],
            ['code' => 'MKD', 'name' => 'Denar', 'aliases' => []],
            ['code' => 'MMK', 'name' => 'Kyat', 'aliases' => []],
            ['code' => 'MNT', 'name' => 'Tugrik', 'aliases' => []],
            ['code' => 'MOP', 'name' => 'Pataca', 'aliases' => []],
            ['code' => 'MRU', 'name' => 'Ouguiya', 'aliases' => []],
            ['code' => 'MUR', 'name' => 'Mauritius Rupee', 'aliases' => []],
            ['code' => 'MVR', 'name' => 'Rufiyaa', 'aliases' => []],
            ['code' => 'MWK', 'name' => 'Malawi Kwacha', 'aliases' => []],
            ['code' => 'MXN', 'name' => 'Mexican Peso', 'aliases' => ['MX$']],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'aliases' => ['RM', 'رينغيت']],
            ['code' => 'MZN', 'name' => 'Mozambique Metical', 'aliases' => []],
            ['code' => 'NAD', 'name' => 'Namibia Dollar', 'aliases' => []],
            ['code' => 'NGN', 'name' => 'Naira', 'aliases' => ['₦']],
            ['code' => 'NIO', 'name' => 'Cordoba Oro', 'aliases' => []],
            ['code' => 'NOK', 'name' => 'Norwegian Krone', 'aliases' => []],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'aliases' => []],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'aliases' => ['NZ$']],
            ['code' => 'OMR', 'name' => 'Rial Omani', 'aliases' => ['ريال عماني', 'ر.ع']],
            ['code' => 'PAB', 'name' => 'Balboa', 'aliases' => []],
            ['code' => 'PEN', 'name' => 'Sol', 'aliases' => []],
            ['code' => 'PGK', 'name' => 'Kina', 'aliases' => []],
            ['code' => 'PHP', 'name' => 'Philippine Peso', 'aliases' => ['₱']],
            ['code' => 'PKR', 'name' => 'Pakistan Rupee', 'aliases' => ['روبية باكستانية']],
            ['code' => 'PLN', 'name' => 'Zloty', 'aliases' => ['zł']],
            ['code' => 'PYG', 'name' => 'Guarani', 'aliases' => []],
            ['code' => 'QAR', 'name' => 'Qatari Rial', 'aliases' => ['ريال قطري', 'ر.ق']],
            ['code' => 'RON', 'name' => 'Romanian Leu', 'aliases' => []],
            ['code' => 'RSD', 'name' => 'Serbian Dinar', 'aliases' => []],
            ['code' => 'RUB', 'name' => 'Russian Ruble', 'aliases' => ['₽', 'روبل']],
            ['code' => 'RWF', 'name' => 'Rwanda Franc', 'aliases' => []],
            ['code' => 'SAR', 'name' => 'Saudi Riyal', 'aliases' => ['ريال', 'ر.س', 'ريال سعودي', 'SR', 'ر.س.']],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'aliases' => []],
            ['code' => 'SCR', 'name' => 'Seychelles Rupee', 'aliases' => []],
            ['code' => 'SDG', 'name' => 'Sudanese Pound', 'aliases' => ['جنيه سوداني']],
            ['code' => 'SEK', 'name' => 'Swedish Krona', 'aliases' => []],
            ['code' => 'SGD', 'name' => 'Singapore Dollar', 'aliases' => ['S$']],
            ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'aliases' => []],
            ['code' => 'SLE', 'name' => 'Leone', 'aliases' => []],
            ['code' => 'SOS', 'name' => 'Somali Shilling', 'aliases' => []],
            ['code' => 'SRD', 'name' => 'Surinam Dollar', 'aliases' => []],
            ['code' => 'SSP', 'name' => 'South Sudanese Pound', 'aliases' => []],
            ['code' => 'STN', 'name' => 'Dobra', 'aliases' => []],
            ['code' => 'SVC', 'name' => 'El Salvador Colon', 'aliases' => []],
            ['code' => 'SYP', 'name' => 'Syrian Pound', 'aliases' => ['ليرة سورية', 'ل.س']],
            ['code' => 'SZL', 'name' => 'Lilangeni', 'aliases' => []],
            ['code' => 'THB', 'name' => 'Baht', 'aliases' => ['฿']],
            ['code' => 'TJS', 'name' => 'Somoni', 'aliases' => []],
            ['code' => 'TMT', 'name' => 'Turkmenistan New Manat', 'aliases' => []],
            ['code' => 'TND', 'name' => 'Tunisian Dinar', 'aliases' => ['دينار تونسي', 'د.ت']],
            ['code' => 'TOP', 'name' => 'Pa anga', 'aliases' => []],
            ['code' => 'TRY', 'name' => 'Turkish Lira', 'aliases' => ['₺', 'ليرة تركية', 'TL']],
            ['code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'aliases' => []],
            ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'aliases' => ['NT$']],
            ['code' => 'TZS', 'name' => 'Tanzanian Shilling', 'aliases' => []],
            ['code' => 'UAH', 'name' => 'Hryvnia', 'aliases' => ['₴']],
            ['code' => 'UGX', 'name' => 'Uganda Shilling', 'aliases' => []],
            ['code' => 'USD', 'name' => 'US Dollar', 'aliases' => ['$', 'دولار', 'دولار أمريكي']],
            ['code' => 'UYU', 'name' => 'Peso Uruguayo', 'aliases' => []],
            ['code' => 'UZS', 'name' => 'Uzbekistan Sum', 'aliases' => []],
            ['code' => 'VES', 'name' => 'Bolívar Soberano', 'aliases' => []],
            ['code' => 'VND', 'name' => 'Dong', 'aliases' => ['₫']],
            ['code' => 'VUV', 'name' => 'Vatu', 'aliases' => []],
            ['code' => 'WST', 'name' => 'Tala', 'aliases' => []],
            ['code' => 'XAF', 'name' => 'CFA Franc BEAC', 'aliases' => []],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'aliases' => []],
            ['code' => 'XOF', 'name' => 'CFA Franc BCEAO', 'aliases' => []],
            ['code' => 'XPF', 'name' => 'CFP Franc', 'aliases' => []],
            ['code' => 'YER', 'name' => 'Yemeni Rial', 'aliases' => ['ريال يمني', 'ر.ي']],
            ['code' => 'ZAR', 'name' => 'Rand', 'aliases' => ['R']],
            ['code' => 'ZMW', 'name' => 'Zambian Kwacha', 'aliases' => []],
            ['code' => 'ZWL', 'name' => 'Zimbabwe Dollar', 'aliases' => []],
        ];

        foreach ($currencies as $currency) {
            CurrencyMap::updateOrCreate(
                ['code' => $currency['code']],
                [
                    'name' => $currency['name'],
                    'aliases' => !empty($currency['aliases']) ? $currency['aliases'] : null,
                ]
            );
        }
    }
}
